FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env-des


WORKDIR /app

# downgrade TLS for SQL Server 2008 to connect (pre SP3)
RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/' /etc/ssl/openssl.cnf \
RUN sed -i 's/CipherString = DEFAULT@SECLEVEL=2/CipherString = DEFAULT@SECLEVEL=1/' /etc/ssl/openssl.cnf
EXPOSE 8080

COPY *.csproj .
RUN dotnet restore


COPY . .

RUN dotnet build --configuration Release --no-restore

RUN dotnet publish -c Release --no-build --output /app/publish


FROM mcr.microsoft.com/dotnet/aspnet:5.0


WORKDIR /app


COPY --from=build-env-des /app/publish .


ENTRYPOINT ["dotnet", "Conectividad.dll"]
