FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env-des


WORKDIR /app


COPY *.csproj .
RUN dotnet restore


COPY . .

RUN dotnet build --configuration Release --no-restore

RUN dotnet publish -c Release --no-build --output /app/publish


FROM mcr.microsoft.com/dotnet/aspnet:5.0


WORKDIR /app


COPY --from=build-env-des /app/publish .


EXPOSE 8080


ENTRYPOINT ["dotnet", "Conectividad.dll"]
