FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env-des


WORKDIR /app

EXPOSE 8080
RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /etc/ssl/openssl.cnf
RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /usr/lib/ssl/openssl.cnf

COPY *.csproj .
RUN dotnet restore


COPY . .

RUN dotnet build --configuration Release --no-restore

RUN dotnet publish -c Release --no-build --output /app/publish


FROM mcr.microsoft.com/dotnet/aspnet:5.0


WORKDIR /app


COPY --from=build-env-des /app/publish .


ENTRYPOINT ["dotnet", "Conectividad.dll"]
